### ISSUE TITLE
fix logo appearance

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_threefold#137] opened 2020-05-13 09:54 UTC
<img width="39" alt="Screenshot 2020-05-13 at 11 53 07" src="https://user-images.githubusercontent.com/54844940/81798531-726d4300-9510-11ea-9dca-6042c17a7ee9.png">

looks unprofessional

**Comment by VonSub** [comment] 2020-05-13 12:56
duplicate of the favicon issue

**Closed by VonSub** 2020-05-13 12:56 UTC
